version: "3.7"
services:
  users:
    restart: always
    image: pabloszx/learner-model-gql
    ports:
      - 3002:3002
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm -r start --filter=service-users
  actions:
    restart: always
    image: pabloszx/learner-model-gql
    ports:
      - 3003:3003
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm -r start --filter=service-actions
  content:
    restart: always
    image: pabloszx/learner-model-gql
    ports:
      - 3004:3004
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm -r start --filter=service-content
  domain:
    restart: always
    image: pabloszx/learner-model-gql
    ports:
      - 3005:3005
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm -r start --filter=service-domain
  projects:
    restart: always
    image: pabloszx/learner-model-gql
    ports:
      - 3006:3006
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm -r start --filter=service-projects
  state:
    restart: always
    image: pabloszx/learner-model-gql
    ports:
      - 3007:3007
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm -r start --filter=service-state
  gateway:
    restart: always
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm -r start --filter=service-gateway
