version: "3.7"
services:
  users:
    restart: always
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm --filter=service-users -r start
  actions:
    restart: always
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm --filter=service-actions -r start
  content:
    restart: always
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm --filter=service-content -r start
  domain:
    restart: always
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm --filter=service-domain -r start
  projects:
    restart: always
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm --filter=service-projects -r start
  state:
    restart: always
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
    command: pnpm --filter=service-state -r start
  gateway:
    restart: always
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
      ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL}
    command: pnpm --filter=service-gateway -r start
  migration:
    restart: "no"
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: pnpm -r migrate:deploy
