version: "3.7"
services:
  dev:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: pabloszx/learner-model-gql
    ports:
      - 3002:3002
      - 3003:3003
      - 3004:3004
      - 3005:3005
      - 3006:3006
      - 3007:3007
      - 8080:8080
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
