version: "3.7"
services:
  # users:
  #   restart: always
  #   image: pabloszx/learner-model-gql
  #   network_mode: host
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     AUTH0_DOMAIN: ${AUTH0_DOMAIN}
  #     AUTH0_CLIENT: ${AUTH0_CLIENT}
  #     AUTH0_SECRET: ${AUTH0_SECRET}
  #   command: pnpm -r start --filter=service-users
  # actions:
  #   restart: always
  #   image: pabloszx/learner-model-gql
  #   network_mode: host
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     AUTH0_DOMAIN: ${AUTH0_DOMAIN}
  #     AUTH0_CLIENT: ${AUTH0_CLIENT}
  #     AUTH0_SECRET: ${AUTH0_SECRET}
  #   command: pnpm -r start --filter=service-actions
  # content:
  #   restart: always
  #   image: pabloszx/learner-model-gql
  #   network_mode: host
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     AUTH0_DOMAIN: ${AUTH0_DOMAIN}
  #     AUTH0_CLIENT: ${AUTH0_CLIENT}
  #     AUTH0_SECRET: ${AUTH0_SECRET}
  #   command: pnpm -r start --filter=service-content
  # domain:
  #   restart: always
  #   image: pabloszx/learner-model-gql
  #   network_mode: host
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     AUTH0_DOMAIN: ${AUTH0_DOMAIN}
  #     AUTH0_CLIENT: ${AUTH0_CLIENT}
  #     AUTH0_SECRET: ${AUTH0_SECRET}
  #   command: pnpm -r start --filter=service-domain
  # projects:
  #   restart: always
  #   image: pabloszx/learner-model-gql
  #   network_mode: host
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     AUTH0_DOMAIN: ${AUTH0_DOMAIN}
  #     AUTH0_CLIENT: ${AUTH0_CLIENT}
  #     AUTH0_SECRET: ${AUTH0_SECRET}
  #   command: pnpm -r start --filter=service-projects
  # state:
  #   restart: always
  #   image: pabloszx/learner-model-gql
  #   network_mode: host
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     AUTH0_DOMAIN: ${AUTH0_DOMAIN}
  #     AUTH0_CLIENT: ${AUTH0_CLIENT}
  #     AUTH0_SECRET: ${AUTH0_SECRET}
  #   command: pnpm -r start --filter=service-state
  # gateway:
  # restart: always
  # image: pabloszx/learner-model-gql
  # network_mode: host
  # environment:
  #   DATABASE_URL: ${DATABASE_URL}
  #   AUTH0_DOMAIN: ${AUTH0_DOMAIN}
  #   AUTH0_CLIENT: ${AUTH0_CLIENT}
  #   AUTH0_SECRET: ${AUTH0_SECRET}
  #   ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL}
  # command: pnpm -r start --filter=service-gateway
  mono:
    restart: always
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
      ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL}
    command: pnpm -r start --filter=mono
  migration:
    restart: "no"
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: pnpm -r migrate:deploy
