version: "3.7"
services:
  mono:
    restart: always
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT: ${AUTH0_CLIENT}
      AUTH0_SECRET: ${AUTH0_SECRET}
      ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL}
    command: pnpm --filter=mono -r start
  migration:
    restart: "no"
    image: pabloszx/learner-model-gql
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: pnpm -r migrate:deploy
